
        select distinct ?n where{
            ?n a <http://dbpedia.org/ontology/HotSpring>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://ja.dbpedia.org/property/泉質> ?o2.
?n <http://ja.dbpedia.org/property/読み仮名> ?o3.
?n <https://schema.org/address> ?o4.
?n <https://schema.org/name> ?o5.
?n <https://schema.org/description> ?o6.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=1) && (count(distinct ?o5)=1) && (count(distinct ?o6)=1)
        )
    
