SELECT ?var1  ?var2Label  ?var3  ?var4  ?var5 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P170>  <http://www.wikidata.org/entity/Q61064> .
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P18>  ?var3 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P276>  ?var4 .
 }
 OPTIONAL {
  ?var4  <http://www.wikidata.org/prop/direct/P625>  ?var5 .
 }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en,en".
  }
}
LIMIT 100
