SELECT ?var1  ?var2  ?var3  ?var4 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q185441> .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
    ?var1  <http://www.w3.org/2000/01/rdf-schema#label>  ?var2 .
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "de".
    ?var1  <http://www.w3.org/2000/01/rdf-schema#label>  ?var3 .
    <http://www.bigdata.com/queryHints#Prior>  <http://www.bigdata.com/queryHints#runLast>     False
.
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "fr".
    ?var1  <http://www.w3.org/2000/01/rdf-schema#label>  ?var4 .
    <http://www.bigdata.com/queryHints#Prior>  <http://www.bigdata.com/queryHints#runLast>     False
.
  }
}
