
        select distinct  ?o1 ?o2 ?o3 ?o4 ?o5 ?o6 ?o7 ?o8 ?o9 ?o10 ?o11 ?o12 ?o13 ?o14 ?o15 ?o16 ?o17 ?o18 ?o19 ?o20 ?o21 ?o22 ?o23 ?o24 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://purl.org/dc/terms/modified> ?o2.
?n <http://purl.org/dc/terms/created> ?o3.
?n <http://www.w3.org/2004/02/skos/core#relatedMatch> ?o4.
?n <http://www.w3.org/2008/05/skos-xl#prefLabel> ?o5.
?o5 <http://www.w3.org/2008/05/skos-xl#literalForm> ?o6.
?o5 <http://ndl.go.jp/dcndl/terms/transcription> ?o7.
?n <http://www.w3.org/2000/01/rdf-schema#label> ?o8.
?n <http://www.w3.org/2002/07/owl#sameAs> ?o9.
?n <http://www.w3.org/2008/05/skos-xl#altLabel> ?o10.
?o10 <http://www.w3.org/2008/05/skos-xl#literalForm> ?o11.
?n <http://www.w3.org/2004/02/skos/core#broader> ?o14.
?n <http://purl.org/dc/terms/source> ?o15.
?n <http://www.w3.org/2004/02/skos/core#inScheme> ?o17.
?n <http://www.w3.org/2004/02/skos/core#closeMatch> ?o18.

            filter (?n = <http://id.ndl.go.jp/auth/ndlsh/00567903>)
        }
    
