
        select distinct ?n where{
            ?n a <https://schema.org/Hotel>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <https://schema.org/address> ?o2.
?n <https://schema.org/name> ?o3.
?n <https://schema.org/description> ?o4.
?n <http://ja.dbpedia.org/property/郵便番号> ?o5.
?n <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?o6.
?n <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?o7.
?n <https://schema.org/image> ?o8.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=1) && (count(distinct ?o5)=1) && (count(distinct ?o6)=1) && (count(distinct ?o7)=1) && (count(distinct ?o8)=1)
        )
    
