SELECT DISTINCT ?var1 
WHERE {
  ?var1 ( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> *) ?var2 .
  ?var1  <http://www.wikidata.org/prop/direct/P1082>  ?var3 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "fr,en".
  }
}
ORDER BY  DESC( ?var3 )
LIMIT 1000
