SELECT DISTINCT ?var1  ?var2 
WHERE {
  ?var1 ( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> *) <http://www.wikidata.org/entity/Q515> .
 SERVICE  <http://wikiba.se/ontology#around>   {
    ?var1  <http://www.wikidata.org/prop/direct/P625>  ?var3 .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#center>  "string1"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#radius>  "20".
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#distance>  ?var2 .
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
}
ORDER BY ASC( ?var2 )
