SELECT ?var1 
WHERE {
  ?var2  <http://www.wikidata.org/prop/direct/P150> * ?var1 .
  ?var2 ( <http://www.wikidata.org/prop/direct/P171> | <http://www.wikidata.org/prop/direct/P273> | <http://www.wikidata.org/prop/direct/P75> | <http://www.wikidata.org/prop/direct/P76> | <http://www.wikidata.org/prop/direct/P77> | <http://www.wikidata.org/prop/direct/P70> | <http://www.wikidata.org/prop/direct/P71> | <http://www.wikidata.org/prop/direct/P74> | <http://www.wikidata.org/prop/direct/P89> )* <http://www.wikidata.org/entity/Q729> .
}
