SELECT DISTINCT ?var1  ?var2Label 
WHERE {
  ?var1 ( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> *) ?var3 .
  ?var1  <http://www.wikidata.org/prop/P17>  ?var4 .
  ?var4  <http://www.w3.org/2000/01/rdf-schema#label>  ?var2Label .
}
LIMIT 10
