SELECT DISTINCT ?var1Label 
WHERE {
  ?var2  <http://www.wikidata.org/prop/direct/P279> * ?var1 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
}
