SELECT ?var1  ?var1Label  ?var2 
WHERE {
 SERVICE  <http://wikiba.se/ontology#around>   {
    ?var1  <http://www.wikidata.org/prop/direct/P625>  ?var2 .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#center>  "string1"^^<http://www.opengis.net/ont/geosparql#wktLiteral> .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#radius>  "20".
  }
  ?var3 ( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> *) <http://www.wikidata.org/entity/Q515> .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
}
LIMIT 10
