
        select distinct ?n where{
            ?n a <http://xmlns.com/foaf/0.1/Organization>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://xmlns.com/foaf/0.1/name> ?o2.
?n <http://RDVocab.info/ElementsGr2/dateOfEstablishment> ?o3.
?n <http://RDVocab.info/ElementsGr2/corporateHistory> ?o4.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=1)
        )
    
