SELECT ?var1  ?var2 
WHERE {
  ?var2  <http://www.wikidata.org/prop/direct/P106> * <http://www.wikidata.org/entity/Q82955> ;
 <http://www.wikidata.org/prop/direct/P19>  <http://www.wikidata.org/entity/Q36> .
}
LIMIT 10
