SELECT ?var1  ?var2 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P131>  <http://www.wikidata.org/entity/Q1524> .
 SERVICE  <http://wikiba.se/ontology#around>   {
    ?var1  <http://www.wikidata.org/prop/direct/P625>  ?var2 .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#center>  <http://www.wikidata.org/entity/Q1524> .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#radius>  "100".
  }
}
