SELECT DISTINCT ?var1  ?var1Label 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P170>  <http://www.wikidata.org/entity/Q301> .
 SERVICE  <http://dbpedia.org/sparql>   {
    ?var2  <http://www.w3.org/2002/07/owl#sameAs>  ?var1 .
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>      ( "es, en").
  }
}
