SELECT ?var1 
WHERE {
  ?var2  <http://www.wikidata.org/prop/direct/P577>  ?var1 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en,en".
  }
}
ORDER BY ASC( ?var1 )
LIMIT 1
