SELECT ?var1  ?var1Label 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P166>  <http://www.wikidata.org/entity/Q18844377> .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#servicePAram>  <http://wikiba.se/ontology#language>  "en.en".
  }
}
