SELECT ?var1  ?var1Label 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q7935> .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#servicePQ7935aram>  <http://wikiba.se/ontology#language>  "pl,en".
  }
}
