SELECT ?var1  ?var1Label 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "de,de".
  }
  ?var1  <http://www.wikidata.org/prop/direct/P31>  ?var2 .
}
LIMIT 100
