SELECT ?var1  ?var1Label 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P22>  <http://www.wikidata.org/entity/Q1339> ;
 <http://www.wikidata.org/prop/direct/P25>  <http://www.wikidata.org/entity/Q57487> ;
 <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q36834> ;
 <http://www.wikidata.org/prop/direct/P106>  <http://www.wikidata.org/entity/Q486748> .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviveParam>  <http://wikiba.se/ontology#language>  "simple".
  }
}
