SELECT ?var1  ?var2Label 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .
  ?var1  <http://www.wikidata.org/prop/direct/P166>  ?var2 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
 {
  SELECT ?var1  ?var2Label 
  WHERE   {
    ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .
    ?var1  <http://www.wikidata.org/prop/direct/P166>  ?var2 .
   SERVICE  <http://wikiba.se/ontology#label>     {
      <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
    }
  }
  LIMIT 10
 }
}
