SELECT DISTINCT ?var1 
WHERE {
  ?var2  <http://www.wikidata.org/prop/direct/P31>  ?var1 .
  ?var3  <http://www.wikidata.org/prop/direct/P31>  ?var2 .
  ?var4  <http://www.wikidata.org/prop/direct/P31>  ?var3 .
  ?var5  <http://www.wikidata.org/prop/direct/P31>  ?var4 .
}
