
        select distinct  ?o1 ?o2 ?o3 ?o4 ?o5 ?o6 ?o7 ?o8 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <http://ja.dbpedia.org/property/泉質> ?o2.
?n <http://ja.dbpedia.org/property/読み仮名> ?o3.
?n <https://schema.org/address> ?o4.
?n <https://schema.org/name> ?o5.
?n <https://schema.org/description> ?o6.

            filter (?n = <https://mdlab.slis.tsukuba.ac.jp/onsen/resource/onsen_Kumamoto70>)
        }
    
