SELECT ?var1  ?var1Label  ?var2 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .
  ?var1 ( <http://www.wikidata.org/prop/direct/P106> / <http://www.wikidata.org/prop/direct/P279> ) <http://www.wikidata.org/entity/Q639669> .
  ?var1  <http://www.wikidata.org/prop/direct/P569>  ?var3 .
  ?var1  <http://www.wikidata.org/prop/direct/P570>  ?var4 .
  ?var5  <http://www.wikidata.org/prop/direct/P734>  ?var5 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "fr,en".
  }
}
