
        select distinct ?n where{
            ?n a <http://dbpedia.org/ontology/ambassador>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <https://schema.org/name> ?o2.
?n <http://seiyu-lod.org/ontology/voicedBy> ?o3.
?n <https://schema.org/creator> ?o4.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=1)
        )
    
