SELECT ?var1  ?var2  ?var1Label  ?var3  ?var4 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "fr,en".
  }
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q43229> .
  ?var1  <http://www.wikidata.org/prop/direct/P279>  ?var2 .
  ?var3  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q142> .
  ?var3  <http://www.wikidata.org/prop/direct/P279>  ?var4 .
}
LIMIT 100
