SELECT ?var1  ?var1Label  ?var2 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P54>  <http://www.wikidata.org/entity/Q191264> .
  ?var1  <http://www.wikidata.org/prop/direct/P18>  ?var2 .
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "nl".
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "nl,en".
  }
}
