
        select distinct ?n where{
            ?n a <https://schema.org/Person>.
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <https://schema.org/name> ?o2.

            
        }GROUP BY ?n
        HAVING (
            (count(distinct ?o1)=1) && (count(distinct ?o2)=1)
        )
    
