SELECT ?var1  ?var1Label  ?var2  ?var3 
WHERE {
  <http://www.wikidata.org/entity/Q64>  <http://www.wikidata.org/prop/direct/P625>  ?var4 .
 SERVICE  <http://wikiba.se/ontology#around>   {
    ?var1  <http://www.wikidata.org/prop/direct/P625>  ?var3 .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#center>  ?var4 .
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#radius>  "50".
  }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "de,en".
  }
  ?var1 ( <http://www.wikidata.org/prop/direct/P31> |( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> )) <http://www.wikidata.org/entity/Q879050> .
  ?var1  <http://www.wikidata.org/prop/direct/P31>  ?var2 .
}
ORDER BY ASC( ?var3 )
