SELECT ?var1  ?var1Label  ?var2 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q13442814> .
  ?var1  <http://www.wikidata.org/prop/direct/P2093>  ?var2 .
 FILTER (  (  CONTAINS (  STR (  ?var2  ) , "Harrowell" )  ) 
) .
 FILTER (  (  CONTAINS (  STR (  ?var2  ) , "P" )  ) 
) .
}
LIMIT 300
