SELECT ?var1  ?var1Label  ?var2 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en,en".
  }
  ?var1 ( <http://www.wikidata.org/prop/direct/P31> / <http://www.wikidata.org/prop/direct/P279> *) <http://www.wikidata.org/entity/Q7275> .
  ?var3  <http://www.wikidata.org/prop/P1082>  ?var4 .
}
LIMIT 100
