#Web NDL authoritiesに対するGROUP_BY_HAVINGを利用したクエリ(目的語の数を指定)

select distinct ?n where
{
    ?n a <http://www.w3.org/2004/02/skos/core#Concept>.        
    ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
    ?n <http://purl.org/dc/terms/modified> ?o2.
    ?n <http://purl.org/dc/terms/created> ?o3.
    ?n <http://www.w3.org/2004/02/skos/core#relatedMatch> ?o4.
    ?n <http://www.w3.org/2008/05/skos-xl#prefLabel> ?o5.
    ?n <http://www.w3.org/2000/01/rdf-schema#label> ?o8.
    ?n <http://www.w3.org/2002/07/owl#sameAs> ?o9.
    ?n <http://www.w3.org/2008/05/skos-xl#altLabel> ?o10.
    ?n <http://www.w3.org/2004/02/skos/core#broader> ?o14.
    ?n <http://purl.org/dc/terms/source> ?o15.
    ?n <http://www.w3.org/2004/02/skos/core#inScheme> ?o17.
    ?n <http://www.w3.org/2004/02/skos/core#closeMatch> ?o18.
    {
        select distinct ?o5 where
        {
            ?o5 <http://www.w3.org/2008/05/skos-xl#literalForm> ?o6.
            ?o5 <http://ndl.go.jp/dcndl/terms/transcription> ?o7.
        }
        GROUP BY ?o5
        HAVING 
        (
            (count(distinct ?o6)=1) && (count(distinct ?o7)=2)
        )
    }
    {
        select distinct ?o10 where{
            ?o10 <http://www.w3.org/2008/05/skos-xl#literalForm> ?o11.
        }
        GROUP BY ?o10
        HAVING 
        (
            (count(distinct ?o11)=1)
        )
    }
}
GROUP BY ?n
HAVING 
(
    (count(distinct ?o1)=1) && (count(distinct ?o2)=1) && (count(distinct ?o3)=1) && (count(distinct ?o4)=3) && (count(distinct ?o5)=1) && (count(distinct ?o8)=1) && (count(distinct ?o9)=1) && (count(distinct ?o10)=1) && (count(distinct ?o14)=1) && (count(distinct ?o15)=2) && (count(distinct ?o17)=1) && (count(distinct ?o18)=1)
)