select distinct  ?n 
where{
    ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1;
    <http://purl.org/dc/terms/modified> ?o2;
    <http://purl.org/dc/terms/created> ?o3;
    <http://www.w3.org/2004/02/skos/core#relatedMatch> ?o4;
    <http://www.w3.org/2008/05/skos-xl#prefLabel> [ 
        <http://www.w3.org/2008/05/skos-xl#literalForm> ?o6;
        <http://ndl.go.jp/dcndl/terms/transcription> ?o7
    ].
}

