PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX category-ja: <http://ja.dbpedia.org/resource/Category:>
SELECT DISTINCT ?s
WHERE {
{
?s dcterms:subject ?volley. 
?s dcterms:subject ?cat
}
}
VALUES (?volley) {
(category-ja:バレーボールを題材とした作品)
(category-ja:女子バレーボールを題材とした作品)
(category-ja:バレーボール漫画)
}
