PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
SELECT (IRI(CONCAT("http://ja.dbpedia.org/resource/Category:", ?x, ?label, ?y)) AS ?category)
WHERE {
{
{
<http://ja.dbpedia.org/resource/スポーツ競技一覧> (dbpedia-owl:wikiPageWikiLink/rdfs:label) ?label .
{
VALUES (?x) {
("")
("男子")
("女子")
}

}
}
}
}
VALUES (?y) {
("アニメ")
("を題材とした作品")
}
