SELECT ?var1  ?var2  ?var3 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P106>  ?var2 .
 OPTIONAL {
  ?var2  <http://www.wikidata.org/prop/direct/P18>  ?var3 .
 }
}
ORDER BY ASC( ?var2 )
LIMIT 10000
