SELECT ?var1  ?var2  ?var3  ?var3Label 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "de,en".
  }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P569>  ?var2 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P569>  ?var2 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P106>  ?var3 .
 }
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q6206631> .
}
LIMIT 100
