SELECT ?var1  ?var1Label  ?var2 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en,en".
  }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P17>  ?var3 .
 }
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q515> .
  ?var1  <http://www.wikidata.org/prop/direct/P17>  <http://www.wikidata.org/entity/Q184> .
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P1082>  ?var2 .
 }
}
LIMIT 10
