SELECT ?var1  ?var2  ?var3  ?var4  ?var5  ?var5Label  ?var6  ?var6Label 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en,en".
  }
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q515> .
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P1082>  ?var2 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P2046>  ?var3 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P2044>  ?var4 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P17>  ?var5 .
 }
 OPTIONAL {
  ?var5  <http://www.wikidata.org/prop/direct/P30>  ?var6 .
 }
}
LIMIT 100
