SELECT ?var1Label  ?var2  ?var3  ?var4Label  ?var5  ?var6 
WHERE {
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q11344> ;
 <http://www.wikidata.org/prop/direct/P246>  ?var2 ;
 <http://www.wikidata.org/prop/direct/P1086>  ?var3 ;
 <http://www.wikidata.org/prop/direct/P61>  ?var4 .
 OPTIONAL {
  ?var4  <http://www.wikidata.org/prop/direct/P19>  ?var5 .
 }
 OPTIONAL {
  ?var5  <http://www.wikidata.org/prop/direct/P625>  ?var6 .
 }
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
}
ORDER BY ASC( ?var3 )
