SELECT ?var1  ?var1Label  ?var2  ?var2Label  ?var3  ?var4  ?var4Label  ?var5 
WHERE {
 SERVICE  <http://wikiba.se/ontology#label>   {
    <http://www.bigdata.com/rdf#serviceParam>  <http://wikiba.se/ontology#language>  "en".
  }
  ?var1  <http://www.wikidata.org/prop/direct/P31>  <http://www.wikidata.org/entity/Q5> .
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P1477>  ?var5 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P27>  ?var2 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P569>  ?var3 .
 }
 OPTIONAL {
  ?var1  <http://www.wikidata.org/prop/direct/P19>  ?var4 .
 }
}
