
        select distinct  ?o1 ?o2 ?o3 ?o4 ?o5 where{
            ?n <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?o1.
?n <https://schema.org/name> ?o2.
?n <http://seiyu-lod.org/ontology/voicedBy> ?o3.
?n <https://schema.org/creator> ?o4.

            filter (?n = <https://mdlab.slis.tsukuba.ac.jp/onsen/resource/onsenmusume113>)
        }
    
